-- DROP TABLE CITY CASCADE CONSTRAINTS;
-- DROP TABLE COUNTRY CASCADE CONSTRAINTS;
-- DROP TABLE COUNTRYLANGUAGE CASCADE CONSTRAINTS;

--------------------------------------------------------
--  DDL for Table CITY
--------------------------------------------------------
CREATE TABLE CITY
(	"ID" NUMBER(*,0)  NOT NULL,
     "NAME" VARCHAR2(50 BYTE)  NOT NULL,
     "COUNTRYCODE" CHAR(3 BYTE)  NOT NULL,
	"DISTRICT" VARCHAR2(100 BYTE)  NOT NULL,
	"POPULATION" NUMBER(*,0)  NOT NULL
   );

--------------------------------------------------------
--  DDL for Table COUNTRY
--------------------------------------------------------
CREATE TABLE COUNTRY
(	"CODE" CHAR(3 BYTE) NOT NULL,
	"NAME" VARCHAR2(100 BYTE) NOT NULL,
	"CONTINENT" VARCHAR2(100 BYTE) NOT NULL,
	"REGION" VARCHAR2(100 BYTE) NOT NULL,
	"SURFACEAREA" FLOAT(63) NOT NULL,
	"INDEPYEAR" NUMBER(*,0),
	"POPULATION" NUMBER(*,0) NOT NULL,
	"LIFEEXPECTANCY" FLOAT(63),
	"GNP" NUMBER(*,0),
	"GNPOLD" NUMBER(*,0),
	"LOCALNAME" VARCHAR2(100 BYTE) NOT NULL,
	"GOVERNMENTFORM" VARCHAR2(100 BYTE) NOT NULL,
	"HEADOFSTATE" VARCHAR2(100 BYTE),
	"CAPITAL" NUMBER(*,0),
	"CODE2" CHAR(2 BYTE)
   );

--------------------------------------------------------
--  DDL for Table COUNTRY
--------------------------------------------------------

CREATE TABLE "SPARKMSO"."COUNTRY"
(	"CODE" CHAR(3 BYTE),
	"NAME" VARCHAR2(100 BYTE),
	"CONTINENT" VARCHAR2(100 BYTE),
	"REGION" VARCHAR2(100 BYTE),
	"SURFACEAREA" FLOAT(63),
	"INDEPYEAR" NUMBER(*,0),
	"POPULATION" NUMBER(*,0),
	"LIFEEXPECTANCY" FLOAT(63),
	"GNP" NUMBER(*,0),
	"GNPOLD" NUMBER(*,0),
	"LOCALNAME" VARCHAR2(100 BYTE),
	"GOVERNMENTFORM" VARCHAR2(100 BYTE),
	"HEADOFSTATE" VARCHAR2(100 BYTE),
	"CAPITAL" NUMBER(*,0),
	"CODE2" CHAR(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COUNTRY_PKEY
--------------------------------------------------------

CREATE UNIQUE INDEX "SPARKMSO"."COUNTRY_PKEY" ON "SPARKMSO"."COUNTRY" ("CODE")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table COUNTRY
--------------------------------------------------------

ALTER TABLE "SPARKMSO"."COUNTRY" MODIFY ("CODE" NOT NULL ENABLE);
ALTER TABLE "SPARKMSO"."COUNTRY" MODIFY ("NAME" NOT NULL ENABLE);
ALTER TABLE "SPARKMSO"."COUNTRY" MODIFY ("CONTINENT" NOT NULL ENABLE);
ALTER TABLE "SPARKMSO"."COUNTRY" MODIFY ("REGION" NOT NULL ENABLE);
ALTER TABLE "SPARKMSO"."COUNTRY" MODIFY ("SURFACEAREA" NOT NULL ENABLE);
ALTER TABLE "SPARKMSO"."COUNTRY" MODIFY ("POPULATION" NOT NULL ENABLE);
ALTER TABLE "SPARKMSO"."COUNTRY" MODIFY ("LOCALNAME" NOT NULL ENABLE);
ALTER TABLE "SPARKMSO"."COUNTRY" MODIFY ("GOVERNMENTFORM" NOT NULL ENABLE);
ALTER TABLE "SPARKMSO"."COUNTRY" ADD CONSTRAINT "COUNTRY_PKEY" PRIMARY KEY ("CODE")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COUNTRY
--------------------------------------------------------

ALTER TABLE "SPARKMSO"."COUNTRY" ADD CONSTRAINT "COUNTRY_CAPITAL_FKEY" FOREIGN KEY ("CAPITAL")
    REFERENCES "SPARKMSO"."CITY" ("ID") ENABLE;


--------------------------------------------------------
--  DDL for Table COUNTRYLANGUAGE
--------------------------------------------------------
CREATE TABLE COUNTRYLANGUAGE
(	"COUNTRYCODE" CHAR(3 BYTE),
	"LANGUAGE" VARCHAR2(100 BYTE),
	"ISOFFICIAL" NUMBER(1,0),
	"PERCENTAGE" FLOAT(63)
   );

--------------------------------------------------------
--  DDL for constrains
--------------------------------------------------------

ALTER TABLE city
    ADD CONSTRAINT city_pkey PRIMARY KEY (id);

ALTER TABLE country
    ADD CONSTRAINT country_pkey PRIMARY KEY (code);

ALTER TABLE countrylanguage
    ADD CONSTRAINT countrylanguage_pkey PRIMARY KEY (countrycode, language);

ALTER TABLE country
    ADD CONSTRAINT country_capital_fkey FOREIGN KEY (capital) REFERENCES city(id);

ALTER TABLE countrylanguage
    ADD CONSTRAINT countrylanguage_countrycode_fkey FOREIGN KEY (countrycode) REFERENCES country(code);

COMMIT;

--ANALYZE;



